# Function for performing wavelet or loess transformation of LRR values
# Requires individual data file and map file (for SNP positions)
# Assumes data file has been generated by previous functions, otherwise
# should include the following (with headers, but in any order): SNP BAF LRR
# Wavelet function written by Tom Fitzgerald
#----------------------------------------------------------------------
adjustLRR <- function(DATAFILE, MAPFILE, outDIR){
	# Preparation
	data = read.table(DATAFILE, h=T, colClasses=c("character","numeric","numeric"))
	data$LRR[is.infinite(data$LRR)] = NA
	map = read.table(MAPFILE, h=F, colClasses=c("numeric","character","numeric"))
	names(map) = c("CHR","SNP","POS")
	data = merge(data,map)
	data = data[order(data$CHR, data$POS),]
	use = is.na(data$BAF) | is.na(data$LRR)
	a = data[!use,]
	# Apply adjustment function
	snpwave <- function (m, odir=outDIR, wFac=1.2){
		# This loads other DDD packages needed to run this function
		source("/nfs/ddd0/software/R/scripts/load_all_packages.R")
		cur = getwd()
		Jpath = system.file("java", package = "CNsolidate")
		wfile1 = paste(odir, "/waveTemp.txt", sep = "")
		wfile2 = paste(odir, "/waveTemp1.txt", sep = "")
		setwd(Jpath)
		u = unique(m$CHR)
		r = NULL
		for (x in 1:length(u)) {
			d = m[m$CHR == u[x], ]
			me = median(d$LRR)
			d$LRR = d$LRR - me
			if (length(d[, 1]) > 5000) {
				write.table(cbind(d$CHR, d$POS, d$POS, d$LRR), file = wfile1, sep = "\t", row.names = F, col.names = F, quote = F)
				command = paste("java -Xmx1600m Wave -f ", wfile1, " -fa ", wFac, " > ", wfile2, sep = "")
				system(command)
				w <- try(read.table(wfile2), silent=T)
				if (inherits(w, 'try-error')){
					write.table(cbind(d$CHR, d$POS, d$POS, d$LRR), file = wfile1, sep = "\t", row.names = F, col.names = F, quote = F)
					command = paste("java -Xmx1600m Wave -f ", wfile1, " -fa ", wFac, " > ", wfile2, sep = "")
					system(command)
					w = read.table(wfile2)
				} 
				d = cbind(d, w[, 3] + me)
				r = rbind(r, d)
			}else {
				r = rbind(r, cbind(d,0))
			}
		}
		names = colnames(m)
		names = c(names, "waveLRR")
		colnames(r) = names
		command = paste("rm ", wfile1, " ", wfile2, sep = "")
		system(command)
		setwd(cur)
		#write.table(r, file = file, sep = "\t", row.names = F, quote = F)
		return(r)
	}
	b <- snpwave(a)
	c = merge(data,subset(b,select=c(SNP,waveLRR)),by="SNP",all.x=T)
	return(subset(c, select=c(SNP,BAF,waveLRR)))
}
